export const ACTIONS = {
    SET_STUDENTS: "SET_STUDENTS",
    UPDATE_STUDENT: "UPDATE_STUDENT",
    SET_TEACHER_LOCATION: "SET_TEACHER_LOCATION",
    SET_STUDENTS_IN_DANGER: "SET_STUDENTS_IN_DANGER",
};

export const nameCorect= /^[a-zA-Z\u0590-\u05FF\s]+$/;